# Generated by Django 5.1.6 on 2025-02-22 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "supplier_id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("supplier_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "inventory_id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("inventory_name", models.CharField(max_length=200)),
                ("inventory_description", models.CharField(max_length=500)),
                ("inventory_note", models.TextField()),
                ("inventory_stock", models.IntegerField(default=0)),
                ("inventory_availability", models.BooleanField(default=True)),
                (
                    "inventory_supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.supplier",
                    ),
                ),
            ],
        ),
    ]
